apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  labels:
    app.kubernetes.io/managed-by: "instancer"
    {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.httproute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  hostnames:
    - "{{ .Release.Name }}.{{ .Values.httproute.hostSuffix }}"
  parentRefs:
    - kind: Gateway
      name: {{ .Values.httproute.gateway }}
      sectionName: {{ .Values.httproute.httpsSectionName }}
  rules:
    - backendRefs:
      - kind: Service
        name: {{ .Release.Name }}
        port: {{ .Values.service.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute-redirect
  labels:
    app.kubernetes.io/managed-by: "instancer"
    {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.httproute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  hostnames:
    - "{{ .Release.Name }}.{{ .Values.httproute.hostSuffix }}"
  parentRefs:
    - kind: Gateway
      name: {{ .Values.httproute.gateway }}
      sectionName: {{ .Values.httproute.httpSectionName }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
