apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: "instancer"
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: "instancer"
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/managed-by: "instancer"
        app.kubernetes.io/name: {{ .Release.Name }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1337
        runAsGroup: 1337
        fsGroup: 1337
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: pwn
              containerPort: {{ .Values.pod.port }}
              protocol: TCP
          {{- if .Values.flag.envkey }}
          env:
            - name: {{ .Values.flag.envkey }}
              value: "{{ .Values.flag.flag }}"
          {{- end }}
          {{- if .Values.flag.path }}
          volumeMounts:
            - name: flag-volume
              mountPath: {{ .Values.flag.path }}
              subPath: flag.txt
          {{- end }}
      volumes:
        {{- if .Values.flag.path }}
        - name: flag-volume
          configMap:
            name: {{ .Release.Name }}-flag
        {{- end }}
