image:
  repository: ghcr.io/dragonsecsi/dctfsi-2025/pwn/flagmanager
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: vuln

pod:
  annotations: {}
  labels: {}
  port: 1337
  securityContext:
    runAsNonRoot: true
    runAsUser: 1337
    runAsGroup: 1337
    fsGroup: 1337
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 64Mi

deployment:
  annotations: {}
  labels: {}

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 1337

volumes: []
  # Example
  # - name: "db"
  #   path: "/app/db"
  #   size: "50Mi"

flag:
  flag: "flag{unset}"
  envkey: "" # If set, the flag will be injected to this environment variable
  path: "" # If set, the flag will be written to this file path
